### ISSUE TITLE
Version tag missing

### ISSUE THREAD

**Issue by dwenzel** [visol/ext-handlebars#19]
Hi,
I just tried to install JFB/Handlebars via 
```
composer require JFB/Handlebars:^1.0.0
```
or 
```
composer require JFB/Handlebars:* 
```
Both ways composer could not find/install the package. 
I guess because the version tag is missing in your repository.

I could only install it as `dev-master` (which is not what I want).
AFAIK the composer package name should be lower case too (´jfb/handlebars´)
It would be great to find the package on packagist.org.

cheers
Dirk

**Comment by SomeBdyElse** [comment]
The extension is available on packagist.org

https://packagist.org/packages/visol/typo3-handlebars
