### ISSUE TITLE
$GLOBALS['BE_USER'] null error (on v8)

### ISSUE THREAD

**Issue by dhuf** [visol/ext-handlebars#2]
`TypeError: Return value of JFB\Handlebars\Engine\HandlebarsEngine::getBackendUser() must be an instance of TYPO3\CMS\Core\Authentication\BackendUserAuthentication, null returned in web/typo3conf/ext/handlebars/Classes/Engine/HandlebarsEngine.php on line 271`

Seems linked to the `[TASK] Add return type for PHP 7` on the `getBackendUser(): BackendUserAuthentication`

**Comment by lorenzulrich** [comment]
Does this happen in FE context or are you using Handlebars for other contexts?

**Comment by dhuf** [comment]
No it is only used in the FE, the $GLOBALS['BE_USER'] does not exist if there is no BE session so the return value is not a BackendUserAuthentication as defined with the PHP 7 type as I understand. Removing the type fixes the issue.

**Comment by lorenzulrich** [comment]
All clear. Could you create a PR for this?

**Comment by dhuf** [comment]
Yes but I don't know if my solution is the best one... this is why I didn't do it https://github.com/dhuf/ext-handlebars/commit/83ea89df5e2f04474b742ede4b4f67be0e64fec0

**Comment by lorenzulrich** [comment]
The fix is absolutely OK like this, but it was mistakenly added as a new commit to another pull request instead of an own PR.

**Comment by lorenzulrich** [comment]
Fixed in acfff6ea44031e1619e09b8cc8cfa0a06af8ffb9.
