### ISSUE TITLE
Do you know if it is v9 Compatible ?

### ISSUE THREAD

**Issue by dhuf** [visol/ext-handlebars#22]

**Comment by jrenggli** [comment]
Currently I don't have any experience regarding compatibility with TYPO3 9. The project this extension originally was developed for is running on TYPO3 8 (for now).

If anyone could test this, please feel free to update the core requirements in `ext_emconf.php` and `composer.json`

**Comment by dhuf** [comment]
We ran into the issue that this extension requires "translationapi" which requires "routing" that is not required or compatible with the v9. We suggest to get rid of the requirement of the "translationapi" by removing the LabelDataProvider. Alternatively we could remove the requirement of "translationapi" to "routing"

**Comment by jrenggli** [comment]
Superseded by #24 24
