### ISSUE TITLE
TYPO3 11 Compatibility

### ISSUE THREAD

**Issue by SomeBdyElse** [visol/ext-handlebars#24]
Hi @dhuf, Hi @jrenggli !

In wonder if you have any plans to make this extension compatible with TYPO3 11 / php 8. I see that there is no requirement for the TYPO3 core in composer.json. There is a requirement for the (abandoned) https://packagist.org/packages/sinso/translationapi and for PHP 7 though.

**Comment by jrenggli** [comment]
Hi @SomeBdyElse

Yes, we have just received funding to ensure compatibility with TYPO3 v11. The related project will start in March 2022.

Please be patient a little longer. And until then Pull Requests are very welcome ;-)

**Comment by DanielSiepmann** [comment]
I see that you released v3.0.0.
But there is no info regarding TYPO3 within `composer.json`. The `composer.json` also does not allow installation with PHP8.0 or 8.1.

Is this already compatible and could you publish v3.0.1 with an updated `composer.json` in that case?

**Comment by DanielSiepmann** [comment]
That's done, I guess this issue can be closed?
