### ISSUE TITLE
Sub partials

### ISSUE THREAD

**Issue by dhuf** [visol/ext-handlebars#4]
Hi, It seems that some sub partials are not loaded with the "lightncandy" module, did you already have this issue ? Thanks

**Comment by dhuf** [comment]
@jrenggli or @fabarea any Idea why this isn't working ? `{{> (lookup . 'partial') data }}` even if it should https://zordius.github.io/HandlebarsCookbook/0028-dynamicpartial.html#precode_S127uFl5Hl with adding: `FLAG_ADVARNAME` and `FLAG_RUNTIMEPARTIAL` even with `FLAG_HANDLEBARSJS_FULL` I don't get a result... 

But the `{{lookup . 'partial'}}` works. Thanks

**Comment by jrenggli** [comment]
@dhuf: Don't know why this is happening. Have you tried some debugging?
The `lookup` helper is defined in https://github.com/visol/ext-handlebars/blob/master/Classes/Engine/HandlebarsEngine.php#L168. Check if this is called.

Personally I don't know this syntax. If you support a snipped with some code that is supposed to work I could probably investigate a little. To fix previous bugs I've spent quite some time debugging in lightncandy already...

**Comment by dhuf** [comment]
A hack is to define them in your template so that they are loaded
```
{{#if false}}
	{{> modules/yourModule/path}}
	{{> modules/yourModule/path}}
	...
{{/if}}
```

**Comment by jrenggli** [comment]
Some technical background: All handlebars templates are compiled to php including all used partials. For every template there will be one file. If you use dynamic partials it's impossible to load these without having them included in the compiled php first.
As zordius/lightncandy parsed the template for all used partials without considering the context you could easily register these in a `{{#if false}}` block as written earlier by @dhuf.
IMHO this block shouldn't affect other applications (e.g. styleguide) using these templates.
